### ISSUE TITLE
Besides nominal data, can ordinal data be used in bar/column charts as well?

### ISSUE THREAD

**Issue by soundquiet** [antvis/AVA#100]
Now all defined charts in BarChart family and ColumnChart family only receive **nominal data** as classification dimension, would it possible to use **ordinal data** as well?
 
As [wiki](https://en.wikipedia.org/wiki/Ordinal_data) mentioned:
> Ordinal data is a categorical, statistical data type where the variables have natural, ordered categories. ... 
The ordinal scale is distinguished from the nominal scale **by having a ranking.**

Maybe it is ok to have ordinal data in bar/column charts?

**Comment by jiazhewang** [comment]
@soundquiet  I agree.

It would be lovely to have a PR for this. Or I would do it, later.

**Comment by soundquiet** [comment]
I'll prepare a PR for it.

**Comment by soundquiet** [comment]
BTW, I think PieCharts can have similar update, too, since piecharts can be replaced in most cases by bar charts.

**Comment by jiazhewang** [comment]
Great! thx!
