### ISSUE TITLE
除了使用拷贝配置按钮获取配置还有别的方法可以直接在代码里获取配置吗

### ISSUE THREAD

**Issue by CahierX** [antvis/AVA#111]
除了使用拷贝配置按钮获取配置还有别的方法可以直接在代码里获取配置吗, 因为需求并不需要用户拷贝配置 而是系统自己获取并渲染

**Comment by jiazhewang** [comment]
如果是这种需求的话，不建议使用 autoChart 方法。可以使用更灵活的 pipeline 定制。参见：https://ava.antv.vision/zh/docs/guide/chart-advisor/pipeline

其中的 [adviceToLibConfig](https://ava.antv.vision/zh/docs/api/chart-advisor/adviceToLibConfig) （原 specToLibConfig）方法可以返回对应的图表库配置。
