### ISSUE TITLE
自定义数据转换为图表的问题

### ISSUE THREAD

**Issue by hyqaimx** [antvis/AVA#114]
最近使用的时候，采用按照规则逐步解析为G2Plot配置的方法，我将G2Plot里的雷达图数据进行转换后advices里并没有雷达图选项，查看了dataPropsToAdvices方法的源码，但还是不明白对应的softScore和hardScore的计算。希望各位可以帮小弟解惑

**Comment by hyqaimx** [comment]
刚刚找到了问题所在，计算出的score是大于0的，但是对应的getChartTypeSpec方法中，对应的雷达图返回被注释掉了
![image](https://user-images.githubusercontent.com/22193405/101338529-1147fb00-38b8-11eb-8e68-46c1591875c7.png)

**Comment by BBSQQ** [comment]
1. hardScore 是强规则分数，如果为 0  则为不推荐；softScore 是弱规则分数，用于在通过 hard 规则之后累加分数。
2. 之所以暂时注释掉雷达图是因为本次 pipeline 支持统一输出到 vega lite specification，如上述 issue 所说 vegaLite 不支持雷达图，我们会尽快支持到雷达图。

**Comment by hyqaimx** [comment]
> 1. hardScore 是强规则分数，如果为 0  则为不推荐；softScore 是弱规则分数，用于在通过 hard 规则之后累加分数。
> 2. 之所以暂时注释掉雷达图是因为本次 pipeline 支持统一输出到 vega lite specification，如上述 issue 所说 vegaLite 不支持雷达图，我们会尽快支持到雷达图。
