### ISSUE TITLE
单行 "integer" 可能误判为 "date"

### ISSUE THREAD

**Issue by BBSQQ** [antvis/AVA#120]
```
const data = [{ 单价: 345333 }];
```

单价字段被认为成时间字段，但是如果多增加几列就没有问题了。

**Comment by hb-bobo** [comment]
可以尝试对key做判定，如date，time，datetimg，日期，或者推荐开发者使用这几个字段

**Comment by neoddish** [comment]
fixed by https://github.com/antvis/AVA/pull/159
