### ISSUE TITLE
Some thumbnails are not available

### ISSUE THREAD

**Issue by SananGuliyev** [antvis/AVA#121]
Hi, 

I wanted to list the thumbnails and I notice that the `Heatmap` and `Histogram` chart thumbnails are not available. The URLs I get from the package:

http://alipay-rmsdeploy-image.cn-hangzhou.alipay.aliyun-inc.com/antfincdn/6fxTNNgLmb/Heatmap.svg
http://alipay-rmsdeploy-image.cn-hangzhou.alipay.aliyun-inc.com/antfincdn/VfwdcWnr0u/Histogram.svg

**Comment by neoddish** [comment]
thx @SananGuliyev ! I am working on that.

**Comment by neoddish** [comment]
We open sourced the thumbnails: https://github.com/antvis/thumbnails

URLs are hard to manage so we use the svg code instead.

**Comment by SananGuliyev** [comment]
Thanks a lot.
