### ISSUE TITLE
一组奇怪的数据，导致无法画出图形

### ISSUE THREAD

**Issue by deadguy15** [antvis/AVA#130]
const region_sales = [
    
   {  btag: 'fav',count:  　997815},
   {  btag: 'pv', count: 　1135028},
   {  btag: 'buy',count:  5388715},
  ];

就是没法画出图形的，但是
 const region_sales = [
    
   {  btag: 'fav',count:  　997815},
   {  btag: 'pv', count: 　1135028},
   {  btag: 'buy',count:  5388715},
 {  btag: 'buy',count:  0},
  ];
就是可以画出图形的

**Comment by neoddish** [comment]
这是个bug，我们修复一下

**Comment by neoddish** [comment]
拆分成了两个问题：

第一个没法画出图形的问题，原因总结到了这里：https://github.com/antvis/AVA/issues/156 会和类似情况一并解决。

第二个问题虽然画出了图形，但是图形很怪异，总结到了这里：https://github.com/antvis/AVA/issues/157

**Comment by neoddish** [comment]
integration test case:  https://github.com/antvis/AVA/pull/155
