### ISSUE TITLE
【Bug】更新到1.1.1 之后，图表不能渲染了，总是报Error: please set the plotType  

### ISSUE THREAD

**Issue by BarronLin** [antvis/AVA#132]
![image](https://user-images.githubusercontent.com/9267731/105702429-bee59b00-5f46-11eb-9559-24ee4a025cd3.png)

**Comment by neoddish** [comment]
具体怎么调用的，代码能贴一下么？

这个错误应该是 autoChart  参数里的 options.config.type 类型不是字符串导致的。

**Comment by BBSQQ** [comment]
可能是触发到了这个地方。但是不知道是哪个 dummy plot 触发的，还是需要具体运行代码
![image](https://user-images.githubusercontent.com/35586469/112451375-62f59200-8d90-11eb-9c2a-7752bb4e7bc0.png)
