### ISSUE TITLE
关于AVA推荐列表的疑问

### ISSUE THREAD

**Issue by haiqinghao** [antvis/AVA#137]
AVA推荐是基于图表知识库的，但是其能够推荐出的图表目前是没有覆盖知识库中所有图表类型的吧？例如力导向图是不是就没有办法推荐。
那这个情况下，不知道在哪里可以找到AVA当前能够推荐的所有图表的列表。
另外AVA目前是都基于G2plot进行推荐对吧，与G2的结合是否有方法。
我是可视化产品经理，问题有不专业的地方请见谅！

**Comment by neoddish** [comment]
1. 确实没有覆盖所有的图表类型，目前只覆盖 G2Plot 支持的主要常用图表类型。类似力导向图的支持正在规划中。
2. 目前支持的图表类型基本可以在[这里](https://github.com/antvis/AVA/blob/master/packages/chart-advisor/src/advice-pipeline/spec-to-libconfig.ts#L27)看到类型 id。考虑到这个需求，我们准备后续在官网文档里放一个目前支持的图表一览。
3. AVA 默认对接的是 G2Plot，但是通过使用 pipeline 组合的形式来修改。比如将 adviceToLibConfig 的参数librayName 设置为 G2，也可以将 g2plotRender 换成 g2Render 从而直接通过 G2 绘制，具体用法可以参考官网文档：https://ava.antv.vision/zh/docs/guide/chart-advisor/pipeline
