### ISSUE TITLE
请问代码如何跑起来

### ISSUE THREAD

**Issue by gb853940223** [antvis/AVA#138]
我将源码下载下来，然后运行npm i，再运行npm start。
报错，如下图：
![image](https://user-images.githubusercontent.com/24557533/109101117-1606a780-7761-11eb-87fb-c0f386d8194f.png)

**Comment by neoddish** [comment]
项目使用 lerna 进行包管理，你需要运行
```lerna bootstrap```

我们会补充一个文档来引导具体相关流程。

**Comment by neoddish** [comment]
请参考这个文档：https://github.com/antvis/AVA/wiki/Development
