### ISSUE TITLE
g2plotRender渲染图表libConfig问题

### ISSUE THREAD

**Issue by gb853940223** [antvis/AVA#139]
用g2plotRender渲染图表时，如何配置libConfig，才可以让图表以指定颜色显示。
我的代码：
export const colors10 = ['#4DBFE8', '#F9A741', '#3B7ECD', '#E0725F', '#ECDEDE', '#07817C', '#1161C8', '#FFE581', '#5ABEF9', '#D87E49',];
![image](https://user-images.githubusercontent.com/24557533/110443211-a4324480-80f6-11eb-9fdd-d9b57ffa35a2.png)
显示效果：
![image](https://user-images.githubusercontent.com/24557533/110443341-c4fa9a00-80f6-11eb-90fe-4b39bd3e9ded.png)
![image](https://user-images.githubusercontent.com/24557533/110443520-f8d5bf80-80f6-11eb-8721-cfc7b3e4e8b8.png)
我的问题：
我设置了同时设置了color10和defaultColor，在多条折线图时，color10的设置生效，但是在单条折线图（或者单条柱形图）时，defaultColor没有生效，因为折线（或柱形）并没有按照color10[0]的颜色进行展现。

**Comment by Esorakouki** [comment]
已反馈给g2plot

可以先通过其他配置项来达成效果
`
theme: {
        styleSheet: {
          brandColor: 'red'
        }
      }
`
