### ISSUE TITLE
Aggregate while auto chart

### ISSUE THREAD

**Issue by neoddish** [antvis/AVA#157]
by issue https://github.com/antvis/AVA/issues/130

The second case:

<img width="1416" alt="Screen Shot 2021-04-29 at 7 10 45 PM" src="https://user-images.githubusercontent.com/6898060/116545092-8e851280-a922-11eb-8c69-cb57e1745ecd.png">

We should consider 'auto agg' during chart recommendation.

**Comment by neoddish** [comment]
integration test case:  https://github.com/antvis/AVA/pull/155

**Comment by GuangMingYouBei** [comment]
#585
