### ISSUE TITLE
相同格式的数据推荐的图表并不一致

### ISSUE THREAD

**Issue by hyqaimx** [antvis/AVA#192]
* **packageName: @antv/chart-advisor**:
* **Version: latest**:
* **os: win10**:
* **CodePen Link**:

在开发当中遇到的一个问题：相同的数据格式下因为数据量不同导致推荐的图表也不一致，当数据量小于100条时不会推荐堆叠的柱状图和条形图，大于100条时会推荐。复现的代码类似这样：

```
const App = () => {
    useEffect(() => {
      const data = Array(30).fill(0).map(item => {
        const obj = {
          str: Math.random().toString(36).slice(-8),
          str2: Math.random() > 0.5 ? 'series1' : 'series2',
          num: Math.floor(Math.random() * 1000)
        }
        return obj;
      });
      const data2 = Array(200).fill(0).map(item => {
        const obj = {
          str: Math.random().toString(36).slice(-8),
          str2: Math.random() > 0.5 ? 'series1' : 'series2',
          num: Math.floor(Math.random() * 1000)
        }
        return obj;
      });
      const dataProps = dataToDataProps(data);
      const dataProps2 = dataToDataProps(data2);
      const advices = dataPropsToAdvices(dataProps);
      const advices2 = dataPropsToAdvices(dataProps2);
      console.log(advices,advices2)
    }, [])
    return <div></div>
  };

  ReactDOM.render(<App />, document.getElementById('container'));
```
我跟了源码之后发现当数据量小于100条时，type方法会解析为Ordinal, 大于时会解析为Nominal。
虽然找到了原因，但是我并不知道怎么解决这个问题（数据量小于100时也推荐堆叠图）,也不清楚为什么要做这样的判断，希望各位能解答，不胜感激

**Comment by neoddish** [comment]
这是一个不错的例子，原因是很复杂的，你的解释从细节来看不完全对。

1. 要判断一个字段是否是 Ordinal （具有顺序性）这件事情是非常难的。我们目前的做法是预设了一些 pattern，比如如果字段是字符串字段，那么如果符合XXX1，XXX2，。。。这种模式（你的 str2 命中了这种模式），会被判断为具有“顺序性”。如果有顺序性，就可以用一些表达顺序的图表类型，比如折线图。

2. 上一条的前提是，这是一个字符串字段。如果认为干脆不是字符串，就不需要做字符串模式判断。这种字段的数据类型的判断的优先级是更高的。然而，我们有一条分析规则是“如果一个字段（基本上）只有两个值，就把它定义为 boolean”。那就不是字符串了。但是这个规则非常武断，很多情况下某个字段其实可以有很多值，只不过恰好当前的数据里只有两个值。这种情况怎么办？我们设置了一个阈值 100，如果你提供的数据集足够多行，超过 100 行，就不太可能是刚才那种巧合了。你的第二个数据命中了这个情况，所以其实他的 str2 已经被认定为是 boolean，就根本不会去判断是不是 ordinal 或 nominal 了。

然后，本质上你会遇到这种问题，是因为你的使用方式和 AVA 目前的设计思路有区别。目前 AVA 图表推荐的假设是数据集是（最终）聚合后、用来直接表达的数据。一般这种数据其实不会太多行。另外，不太会出现你的 str 这种情况。这种 str 其实是一种 id，让他太多的时候，并不适合放在图表中呈现，因为这种类似主键的字段几乎无法被聚合。想象一下，每个 str 要做一根柱子，1000 跟柱子做出来也是看不清的。所以建议解决这个问题。

最后，AVA 目前研发中的先推荐再 lint 的方式应该能部分解决这类问题，我们会持续推进技术方案的优化和升级。

谢谢你的提问！

**Comment by neoddish** [comment]
@antvis/ava-dev-team
