### ISSUE TITLE
The function analyzeDate in package datawizard should return original value of maximum and minimum

### ISSUE THREAD

**Issue by AmyQianqianwang** [antvis/AVA#24]
According to the general design logic, the original data should be returned after an array gets the maximum and minimum value.  

So analyzer.analyzeDate in package datawizard should return original value of maximum and minimum, not the timestamp.

And the case is as follows:

![image](https://user-images.githubusercontent.com/20432533/75319754-32e77100-58a8-11ea-9817-d6d5a5beea37.png)

**Comment by jiazhewang** [comment]
Thx Amy!
I'm closing this since the PR has been merged.
