### ISSUE TITLE
使用@antv/chart-advisor Advisor   传参 fields目前为必填 如果不填 返回advice为空

### ISSUE THREAD

**Issue by beewolf233** [antvis/AVA#269]
* **Package Name**:
* **Package Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

import { Advisor } from '@antv/chart-advisor';
 const myAdvisor = new Advisor();
myAdvisor.advise({data: mockData });

**Comment by soundquiet** [comment]
fixed in #270
