### ISSUE TITLE
antv/chart-advisor引入报错

### ISSUE THREAD

**Issue by Chengchcc** [antvis/AVA#368]
* **Package Name**: @antv/chart-advisor
* **Package Version**: 2.0.0
* **Platform**: windows
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

引入报错， 打包后报错
![image](https://user-images.githubusercontent.com/40747098/142984668-a9df9bb4-58d7-4c99-aea5-bc8430cba961.png)
以及webpack打包后tscheck报错
![image](https://user-images.githubusercontent.com/40747098/142984843-3c532ea8-0e67-4575-afb6-207087efcc3c.png)

**Comment by pddpd** [comment]
@Chengchcc hello，方便把代码放到 CodeSandbox 之类的代码沙盒让我们复现下问题吗

**Comment by baiheinet** [comment]
缺个s
