### ISSUE TITLE
无法启动项目 爆内存溢出 

### ISSUE THREAD

**Issue by chuangwei** [antvis/AVA#370]
* **Package Name**:
* **Package Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

`<--- Last few GCs --->

[48885:0x1046d0000]    78669 ms: Scavenge (reduce) 4064.4 (4072.4) -> 4064.0 (4073.7) MB, 5.6 / 0.0 ms  (average mu = 0.316, current mu = 0.300) allocation failure
[48885:0x1046d0000]    78675 ms: Scavenge (reduce) 4064.7 (4075.7) -> 4064.1 (4076.2) MB, 5.6 / 0.0 ms  (average mu = 0.316, current mu = 0.300) allocation failure
[48885:0x1046d0000]    78681 ms: Scavenge (reduce) 4064.9 (4073.2) -> 4064.3 (4074.2) MB, 4.4 / 0.0 ms  (average mu = 0.316, current mu = 0.300) allocation failure

<--- JS stacktrace --->`

**Comment by BBSQQ** [comment]
执行 `npm run one-stop-setup` 成功了吗？

**Comment by chuangwei** [comment]
> 执行 `npm run one-stop-setup` 成功了吗？

我是通过 npx create-react-app my-app 创建的项目
然后 yarn add @antv/auto-chart
最后 yarn start 无法启动

**Comment by BBSQQ** [comment]
> > 执行 `npm run one-stop-setup` 成功了吗？
> 
> 我是通过 npx create-react-app my-app 创建的项目 然后 yarn add @antv/auto-chart 最后 yarn start 无法启动

好的，已经复现，感谢反馈。

在 v2 版本之后为了让图表推荐能力更纯粹，故将 autoChart 从 chart-advisor 中剥离。但是介于之前 AVA 的用户对 autoChart 的深刻认知，所以将其封装为一个 react 组件进行暴露，但是这个组件的适用场景和侧重点还在探索中。想问一下您这边的场景主要是什么？

**Comment by chuangwei** [comment]
> > > 执行 `npm run one-stop-setup` 成功了吗？
> > 
> > 
> > 我是通过 npx create-react-app my-app 创建的项目 然后 yarn add @antv/auto-chart 最后 yarn start 无法启动
> 
> 好的，已经复现，感谢反馈。
> 
> 在 v2 版本之后为了让图表推荐能力更纯粹，故将 autoChart 从 chart-advisor 中剥离。但是介于之前 AVA 的用户对 autoChart 的深刻认知，所以将其封装为一个 react 组件进行暴露，但是这个组件的适用场景和侧重点还在探索中。想问一下您这边的场景主要是什么？

我在准备再在编译器内添加这个组件，用户可以添加附件解析后自动生成图表。

**Comment by BBSQQ** [comment]
> > > > 执行 `npm run one-stop-setup` 成功了吗？
> > > 
> > > 
> > > 我是通过 npx create-react-app my-app 创建的项目 然后 yarn add @antv/auto-chart 最后 yarn start 无法启动
> > 
> > 
> > 好的，已经复现，感谢反馈。
> > 在 v2 版本之后为了让图表推荐能力更纯粹，故将 autoChart 从 chart-advisor 中剥离。但是介于之前 AVA 的用户对 autoChart 的深刻认知，所以将其封装为一个 react 组件进行暴露，但是这个组件的适用场景和侧重点还在探索中。想问一下您这边的场景主要是什么？
> 
> 我在准备在块编译器内添加这个组件，用户可以添加附件解析后自动生成图表。

好的，感谢。我们将尽快反馈解决方案哈

**Comment by BBSQQ** [comment]
@chuangwei 通过如下方式进行配置，可以在 create-react-app 脚手架中使用：

1. 保证安装 auto-chart 及其所需的 peerDeps，并保证安装最新版本 ^2.0.2
```bash
yarn add @antv/auto-chart antd @antv/g2plot @antv/g6
```
2. 通过 scripts 增加内存；

package.json
```bash
- "start": "react-scripts start",
+ "start": "react-scripts --max_old_space_size=8192 start",
- "build": "react-scripts build",
+ "build": "react-scripts --max_old_space_size=8192 build",
```

当前这个组件的打包方式确实可以继续优化，之后会随着组件使用定位逐步清晰，这个 issue 我先 close 了，如果有兴趣可以关注这个 [issue](https://github.com/antvis/AVA/issues/371)，关于优化暴露方案和打包方案的。
