### ISSUE TITLE
[chart-advisor]support for custom rules and CKB

### ISSUE THREAD

**Issue by Esorakouki** [antvis/AVA#382]
support for custom rules and CKB in data2advices api

**Comment by Cuiyansong** [comment]
请问，目前是否能在不Fork更改源码的情况下，增加Chart Spec吗？（例如，当CKB插件化增加一个新的“图表”，是否能新增对应的Chart Spec）

**Comment by neoddish** [comment]
> 请问，目前是否能在不更改源码的情况下，增加Chart Spec吗？（例如，当CKB插件化增加一个新的“图表”，是否能新增对应的Chart Spec）

可以参考这个案例：https://ava.antv.vision/zh/examples/chart-advisor/advise-and-lint#custom-ckb-rules-ca

在自定义的新图表内指定 toSpec 方法，来说明这种新图表如何映射。
