### ISSUE TITLE
[chart-advisor] The chartAdvisor params `fields` is unreasonable

### ISSUE THREAD

**Issue by BBSQQ** [antvis/AVA#387]
* **Package Name**:
* **Package Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by vaibhav-systango** [comment]
also when I pass data like this, the function `getDataInsights` gets stuck into infinite loop not sure why atleast it should throw error incase it's not able to handle this data and not sure why it's not able to handle this data
 
`[
    {
        "BLOCK_NUMBER": 15034401,
        "BLOCK_HASH": "0xb59ed1d9b6a0facbb20b94b61afc71091b57f33c4f1bc099c0fbc1f87aba2a0d",
        "TIMESTAMP": 1656333572,
        "MINER": "0x1aD91ee08f21bE3dE0BA2ba6918E714dA6B45836",
        "REWARD": 4885574945047367000,
        "REWARD_NUM_VAL": 4885574945047367000,
        "REWARD_NATIVE_VAL": 4.885574945047367,
        "REWARD_NATIVE_VAL_NUM_VAL": 4.885574945047367,
        "DIFFICULTY": 14651600052282136,
        "DIFFICULTY_NUM_VAL": 14651600052282136,
        "TOTAL_DIFFICULTY": 5.270245522925771e+22,
        "TOTAL_DIFFICULTY_NUM_VAL": 5.270245522925771e+22,
        "SIZE": 70526,
        "GAS_USED": 10316139,
        "GAS_LIMIT": 29970590,
        "BASE_FEE_PER_GAS": 32635230490,
        "BASE_FEE_PER_GAS_NUM_VAL": 32635230490,
        "BASE_FEE_PER_GAS_NATIVE_VAL": 3.263523049e-8,
        "BASE_FEE_PER_GAS_NATIVE_VAL_NUM_VAL": 3.263523049e-8,
        "EXTRA_DATA": "486976656f6e20686b",
        "PARENT_HASH": "0x2c8057d10a007f736da0ad0c3798a4c90f4891907ae828c6ce1ac93953bb0853",
        "SHA3_UNCLES": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
        "STATE_ROOT": "0xc8b7baccb27b504be1a1c5b3078dfe7213941c00adca5a558b7e4c0d366cf1c4",
        "NONCE": "0xad5e61cc9b9edfdb",
        "TRANSACTIONS_ROOT": "0x1d5da714a45ce7ff5500e7c29be591d2609a9089930a65fac6e6b06fb99a0e0d",
        "LOGS_BLOOM": "0x16f0524009042c066aa8606da310977153040c6cac0010940c050d197da279869106c0409098040080c7e8890e21231e4a1b383c9e54b784021418889b7e23d000904406009080297824010ac90603600c9c1401ec401c0409c158018001182052179060020749a3a5300a80b1a40c7926621010a10fb4e40341b07ad54b000232400363121350814468011b03b0ac040c1092c74bd0a2c88988814cc1101a8edf42390d0202fc02b88b46cb250a21d7864e840121f1838a63f78806500920895112206e9a4400c10e084824000b520400280756ff1a60583408392a0006ec47199c282802040048199510a961041a440ce11483633e3163004aca0004826433",
        "RECEIPTS_ROOT": "0xdbba755956eaafe1ccb5b765ab91c3bf75245f867e53006b6f40aeba24f94ca1",
        "UNCLES_COUNT": 0,
        "TRANSACTION_COUNT": 129,
        "DECODED": "PARTIAL_DECODED",
        "VERSION": 1
    },
    {
        "BLOCK_NUMBER": 15034402,
        "BLOCK_HASH": "0x1b1d99bf1bc1a689f102509a1ddd1013f59cd9a8a7002206c225b4d7df61f769",
        "TIMESTAMP": 1656333583,
        "MINER": "0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8",
        "REWARD": 5348721809280015000,
        "REWARD_NUM_VAL": 5348721809280015000,
        "REWARD_NATIVE_VAL": 5.348721809280015,
        "REWARD_NATIVE_VAL_NUM_VAL": 5.348721809280015,
        "DIFFICULTY": 14653799075537688,
        "DIFFICULTY_NUM_VAL": 14653799075537688,
        "TOTAL_DIFFICULTY": 5.270246988305679e+22,
        "TOTAL_DIFFICULTY_NUM_VAL": 5.270246988305679e+22,
        "SIZE": 159499,
        "GAS_USED": 29981134,
        "GAS_LIMIT": 29999857,
        "BASE_FEE_PER_GAS": 31364159565,
        "BASE_FEE_PER_GAS_NUM_VAL": 31364159565,
        "BASE_FEE_PER_GAS_NATIVE_VAL": 3.1364159565e-8,
        "BASE_FEE_PER_GAS_NATIVE_VAL_NUM_VAL": 3.1364159565e-8,
        "EXTRA_DATA": "75732d656173742d3130",
        "PARENT_HASH": "0xb59ed1d9b6a0facbb20b94b61afc71091b57f33c4f1bc099c0fbc1f87aba2a0d",
        "SHA3_UNCLES": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
        "STATE_ROOT": "0xce59abac66ce176624afb947e18cd53594742c93aba49fa148e028a8eb7d2a3f",
        "NONCE": "0x9d7ab76315b61f99",
        "TRANSACTIONS_ROOT": "0xfa10318bb1107932a9d926d7d3b40a908124e8e52320fb060732b12bd9833037",
        "LOGS_BLOOM": "0xefe7fbf3bbcefdafbfe874c9f2db4ffbfec7f3fbdf5ac7d0f7ddb7fbfeebffc7feec79edcf1c7f34ef1e5fd174b3fdf7fa69f9f9ee45ffb7dffcdf26ebf664bc7f23da3af9ba3dee79cb3b8ff5f76d79fca3f311ff5df45e7afede7dd747d436fbf5bb7293ff5f37c7d5fcb597fdbcf379ff5adc87ee4fafc2beceff467bf40afbcfc70f7fffbafe4cfd2d6847efefd7ccdf27f38beed92e3d37a5cde3f0f277dfeca3bf57bafe36ffed65ffbdce3fb9ddffeb70cfd3bbebffe78e7efaddd87cf379b66eebe7ebfbae791dfbbfbf5ec716bf33fd7fef5ed7715ffdafa77bfeffddf8ff39ef3c49fcd8d6ffb1abbcdfc327584bfff6fd7dff4eeffab67febf8af",
        "RECEIPTS_ROOT": "0xa44a2a9ac050ad454ff4ad39265079138ea88d790b7a774a77c5b69eb5bcea55",
        "UNCLES_COUNT": 0,
        "TRANSACTION_COUNT": 457,
        "DECODED": "PARTIAL_DECODED",
        "VERSION": 1
    },
    {
        "BLOCK_NUMBER": 15034406,
        "BLOCK_HASH": "0x70521fa0a23a5b22281294377ce8425019fae2afa165a79cbae0ff7dac521448",
        "TIMESTAMP": 1656333680,
        "MINER": "0x829BD824B016326A401d083B33D092293333A830",
        "REWARD": 8570516412483035000,
        "REWARD_NUM_VAL": 8570516412483035000,
        "REWARD_NATIVE_VAL": 8.570516412483034,
        "REWARD_NATIVE_VAL_NUM_VAL": 8.570516412483034,
        "DIFFICULTY": 14626808828686566,
        "DIFFICULTY_NUM_VAL": 14626808828686566,
        "TOTAL_DIFFICULTY": 5.27025283771662e+22,
        "TOTAL_DIFFICULTY_NUM_VAL": 5.27025283771662e+22,
        "SIZE": 65356,
        "GAS_USED": 10670817,
        "GAS_LIMIT": 29999801,
        "BASE_FEE_PER_GAS": 36219387003,
        "BASE_FEE_PER_GAS_NUM_VAL": 36219387003,
        "BASE_FEE_PER_GAS_NATIVE_VAL": 3.6219387003e-8,
        "BASE_FEE_PER_GAS_NATIVE_VAL_NUM_VAL": 3.6219387003e-8,
        "EXTRA_DATA": "e4b883e5bda9e7a59ee4bb99e9b1bc4b3622",
        "PARENT_HASH": "0x52350f3e29d79d298249780409841aefda302ea46e263627fbd996d1b3b5957d",
        "SHA3_UNCLES": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
        "STATE_ROOT": "0x1152b7044946c64bcd24d2e31fbf48f13284a7955e2a536a21ed0ca3bd065984",
        "NONCE": "0x98c88b3297c2630c",
        "TRANSACTIONS_ROOT": "0x70507d2c77d44e4c20a84b108071d44f05f7b562a024b25bb56fa8d1b20bf9ee",
        "LOGS_BLOOM": "0x076912a13846134228080019908452ef920005588d422300249505463a6274dd04df544844788c69cc80d90890040b814aa921218e0aa1650b318607352ca3480d9443610588004ee991020991e0fea41c5bcab4d55400108aca392eca1080a55a07905513ba022ea780a8590c834ecbe063d24434020ef60e05c0f9295a0854c0624745021251801ce802780894bc104f2206e9834c861d17e3044cc0f0a1269e498d351521ec39fc2423d3455b4c043fc2f001239302230aaf1f66da85c900490826470dc0404902a0218a0b0d1246087c70500b0b085c0200b9de006863884036a3ab2a150492a5443bb061a639d40bcc2a65e8fc1562462c8eb2220a50a9",
        "RECEIPTS_ROOT": "0x74ba6a8b557fbabb954bb241d62c65c849a941da170e7aa2dfb72686de6295de",
        "UNCLES_COUNT": 0,
        "TRANSACTION_COUNT": 149,
        "DECODED": "PARTIAL_DECODED",
        "VERSION": 1
    },
    {
        "BLOCK_NUMBER": 15034412,
        "BLOCK_HASH": "0xf6a2ab092168bf89b84faa5dd027254dde72b6a14539d2db75a9f8dbba8a24cf",
        "TIMESTAMP": 1656333741,
        "MINER": "0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8",
        "REWARD": 10885212956459567000,
        "REWARD_NUM_VAL": 10885212956459567000,
        "REWARD_NATIVE_VAL": 10.885212956459569,
        "REWARD_NATIVE_VAL_NUM_VAL": 10.885212956459569,
        "DIFFICULTY": 14654295549841728,
        "DIFFICULTY_NUM_VAL": 14654295549841728,
        "TOTAL_DIFFICULTY": 5.270261621278114e+22,
        "TOTAL_DIFFICULTY_NUM_VAL": 5.270261621278114e+22,
        "SIZE": 50550,
        "GAS_USED": 9225689,
        "GAS_LIMIT": 30000000,
        "BASE_FEE_PER_GAS": 28868427108,
        "BASE_FEE_PER_GAS_NUM_VAL": 28868427108,
        "BASE_FEE_PER_GAS_NATIVE_VAL": 2.8868427108e-8,
        "BASE_FEE_PER_GAS_NATIVE_VAL_NUM_VAL": 2.8868427108e-8,
        "EXTRA_DATA": "6575726f70652d63656e7472616c322d676e7637",
        "PARENT_HASH": "0xa76695800262890157aeeb7f503c0341bb3fe6837d2c823cbf198ed7dba0fce4",
        "SHA3_UNCLES": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
        "STATE_ROOT": "0x6aee81487c541004c21a1d06b4953ba87d275b278bb1dfc333bf11da1863e385",
        "NONCE": "0x149d27311caa11f1",
        "TRANSACTIONS_ROOT": "0xa4f90d9f83ec537517c0920528c03950409a0eb9b8b4ade68a18e8a110ecdcef",
        "LOGS_BLOOM": "0x8c200350590643821e08780896529ae55ac25048a16882092059c884beda70c630ac99082ca85060a116500826058790cb290024bb42b404c8c0942319e4210208a0c2080030008cdba162899d25422324c270a5a1e4880018c20a1681aaa1605e4502969312822e9659910831518e25006140b3202924558442a834cdad6a802280c513c64798c00f6930203728682d88289ea1832c865bc729326b201138149f5825459080284ee84187d3099a0c644082ca0102d5020320e502263401c6c4019903369109ea691ac830d029ba8a84064c0a4b021a4c5400001903104ae5548230a0ab09854e0400067ab304ee3ad2044c5021e0ec107841429835c7424048",
        "RECEIPTS_ROOT": "0x3067958bffcffe1d65b07aa4fc62e3a7eafdb017cbd97dc9604edc6695523a52",
        "UNCLES_COUNT": 0,
        "TRANSACTION_COUNT": 102,
        "DECODED": "PARTIAL_DECODED",
        "VERSION": 1
    }
]`

the function get
@neoddish @WakuWaku-OuO @pddpd @BBSQQ !

**Comment by vaibhav-systango** [comment]
@neoddish

**Comment by BBSQQ** [comment]
getDataInsights? @Esorakouki do you have any idea?

**Comment by LAI-X** [comment]
@vaibhav-systango  There are too many combinations of dimensions, it takes a long time to calculate. Adding such an option solves this problem.
![image](https://user-images.githubusercontent.com/71261480/226168649-b550b5e2-80a3-4890-95d6-b2d5c2bb9a7f.png)
