### ISSUE TITLE
【bug】无指定数据状态下初始化表格，点击 config 后 js 报错

### ISSUE THREAD

**Issue by Michaelooo** [antvis/AVA#39]
### 🐛 bug 描述

无指定数据状态下初始化表格，点击 config 后js报错，如果设置了数据，没有此现象。

### 📷 复现步骤

1. 未指定 data 数据下初始化表格
2. 选择某一个图表类型后，成功渲染
3. 点击 config 后内部 js 报错，流程终止

### 🏞 期望结果

可以继续流程。

### 💻 复现代码

无

### © 版本信息

- @antv/chart-advisor: 0.1.3-alpha.17
- 浏览器环境: chrome 80.0.3987.122
- 开发环境: macOS

### 🚑 其他信息

报错截图：![报错信息](https://i.loli.net/2020/03/09/BJ3QTwF1vIbUgDV.jpg)

**Comment by xiaohuoni** [comment]
不能算bug，传入时机不对。需要等页面渲染了再传入。
```
 useEffect(() => {
    const container = document.getElementById('mountNode') as HTMLElement;
    autoChart(container, data, { toolbar: true, development: true });
  }, []);
```

**Comment by xiaohuoni** [comment]
我装的是  "@antv/chart-advisor": "^0.1.3-alpha.26" 没复现这个问题

**Comment by Michaelooo** [comment]
> 我装的是 "@antv/chart-advisor": "^0.1.3-alpha.26" 没复现这个问题

本机装了 ^0.1.3-alpha.26 后，此问题已修复(之前装的版本是  0.1.3-alpha.17)，可以关闭了。

ps: 我刚特意去试了下，20 的版本应该也是有问题的。[在线 demo]( https://stackblitz.com/edit/react-ava-demo)

**Comment by Michaelooo** [comment]
谢谢回复！

升级了版本之后已经解决了，非常感谢。
我之前直接按照 demo 文件里做的，使用了 ref ，实例化的时候应该是有 Dom 的了。
