### ISSUE TITLE
@antv/chart-advisor problem in vue

### ISSUE THREAD

**Issue by Stavros-Lyras** [antvis/AVA#395]
* **@antv/chart-advisor**:
* **2.0.0**:
* **Vue**:

Hello
When importing ChartAdvisor from @antv/chart-advisor. My console raise an error **Object(...) is not a function**

Thanks in advance

**Comment by BBSQQ** [comment]
Hello, I have tried using vue and chart-advisor in codesandbox (link is https://codesandbox.io/s/chart-advisor-in-vue-845y67?file=/src/App.vue) , it works well. Can you provide more on how to use it?

**Comment by Stavros-Lyras** [comment]
I made a copy of your app and the problem exists. Here is a thumb from my console
![Screenshot 2022-03-17 at 10 18 50 AM](https://user-images.githubusercontent.com/77720065/158766561-90cad2e0-c6ad-43ca-94ac-5c59bc1285ba.png)
and here is a thumb from my package.json
![Screenshot 2022-03-17 at 10 20 18 AM](https://user-images.githubusercontent.com/77720065/158766738-834ef925-fe96-42d0-a016-c0952e60a13d.png)

**Comment by BBSQQ** [comment]
> I made a copy of your app and the problem exists. Here is a thumb from my console ![Screenshot 2022-03-17 at 10 18 50 AM](https://user-images.githubusercontent.com/77720065/158766561-90cad2e0-c6ad-43ca-94ac-5c59bc1285ba.png) and here is a thumb from my package.json ![Screenshot 2022-03-17 at 10 20 18 AM](https://user-images.githubusercontent.com/77720065/158766738-834ef925-fe96-42d0-a016-c0952e60a13d.png)

I used vue/cli to initialize the project locally and it still did not reproduce. Can you provide other key codes to help solve the problem?
In other words, chart advisor is a js library and should not be different for different frameworks.

**Comment by Stavros-Lyras** [comment]
> 

Yes, I know. We use the same lib and in react projects. But the problem raised in vue projects and I don't know the solution.

**Comment by BBSQQ** [comment]
> > 
> 
> Yes, I know. We use the same lib and in react projects. But the problem raised in vue projects and I don't know the solution.

Can you provide the data you used in project?

**Comment by Esorakouki** [comment]
![image](https://user-images.githubusercontent.com/15276351/158787582-43317be3-c238-4a8b-9eaa-c5da67360d6b.png)
@Stavros-Lyras can you show the exact place where the exception occurred

**Comment by Stavros-Lyras** [comment]
> 

I've tried in codesandbox [link](https://codesandbox.io/s/chart-advisor-in-vue-845y67?file=/src/App.vue:0-800) and play well.

The line is here
![Screenshot 2022-03-17 at 12 25 37 PM](https://user-images.githubusercontent.com/77720065/158789645-ed195b7f-c6c3-43b0-b886-8f565650b542.png)
in @antv/data-wizard/esm/analyzer/is-date.js file

**Comment by neoddish** [comment]
> > 
> 
> I've tried in codesandbox [link](https://codesandbox.io/s/chart-advisor-in-vue-845y67?file=/src/App.vue:0-800) and play well.
> 
> The line is here ![Screenshot 2022-03-17 at 12 25 37 PM](https://user-images.githubusercontent.com/77720065/158789645-ed195b7f-c6c3-43b0-b886-8f565650b542.png) in @antv/data-wizard/esm/analyzer/is-date.js file

@pddpd

**Comment by pddpd** [comment]
@Stavros-Lyras Can you put your code in CodeSandbox? I can't reproduce this problem.

**Comment by BBSQQ** [comment]
@pddpd I encountered a similar error when I used dw in another project.
![image](https://user-images.githubusercontent.com/35586469/161511045-3ae03217-95b8-4621-a3b5-7f4a8efe344e.png)

why tslib is devDeps?
![image](https://user-images.githubusercontent.com/35586469/161511414-0d1420ff-30c0-466c-9475-fd5552eb2548.png)

**Comment by pddpd** [comment]
> 



> @pddpd I encountered a similar error when I used dw in another project. ![image](https://user-images.githubusercontent.com/35586469/161511045-3ae03217-95b8-4621-a3b5-7f4a8efe344e.png)
> 
> I think it might be a packaging issue. [antvis/G6#2702](https://github.com/antvis/G6/issues/2702)

It may not be the same problem. DataWizard should move `tslib` from devDep to dep, but this issue uses ChartAdvisor, which itself contains `tslib`. Can you show it in CodeSandbox?
