### ISSUE TITLE
To split the advisor pipeline

### ISSUE THREAD

**Issue by neoddish** [antvis/AVA#40]
The current chart recommending pipeline is  `data > G2Plot`.

The whole process is in one huge function `analyze()`.

For flexibility and expansibility, the pipeline should be splited divided into smaller tubes, like:
`data > data props > chart schema(specification) > library translator > chart code`

There could be api for each step to enable different usages.

**Comment by jiazhewang** [comment]
- [ ] `data -> analyze` change to `data -> data props -> analyze`
- [ ] `analyze -> Advice` change to `analyze -> spec` spec may use vega-lite schema temp.
- [ ] `spec -> G2Plot` translator
- [ ] `spec -> any` translator

**Comment by jiazhewang** [comment]
The graph is ugly but the pipeline could be somethong like this:

![img](https://gw.alipayobjects.com/zos/antfincdn/YBzJnTR4My/avapipeline.png)
