### ISSUE TITLE
SmartBoard test failed

### ISSUE THREAD

**Issue by pddpd** [antvis/AVA#405]
* **Package Name**: smart-board
* **Package Version**: 2.0.0
* **Platform**: Mac v11.2.1,  NPM v.14.17
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/15177000/162576395-bc7d9a96-a9c1-462f-90c6-5aba4afe174e.png)
* **CodePen Link**:

Run `npm run test:sb`, it will throw the error.

**Comment by ArranZeyuWang** [comment]
Fixed in [https://github.com/antvis/AVA/pull/458](url)
