### ISSUE TITLE
配置里面的代码不知道在哪

### ISSUE THREAD

**Issue by xiaohuoni** [antvis/AVA#41]
`https://render.alipay.com/p/s/autoChart/config-panel.html?type=Bubble&cancopydata=false`

请问这部分的代码，在哪里维护？

**Comment by jiazhewang** [comment]
目前这部分配置面板的代码没有开放出来，不过确实应该开放出来，我们想一想怎么个形式比较好~

**Comment by neoddish** [comment]
原先的这部分代码一直没能放出，后来功能也发生了变化。在 v3.1 中我们将重新考虑这个能力。因此先关闭这个 issue。相关问题和信息请关注：https://github.com/antvis/AVA/issues/635
