### ISSUE TITLE
dataToDataProps: big data will cause stack size exceeded

### ISSUE THREAD

**Issue by simaQ** [antvis/AVA#42]
https://github.com/antvis/AVA/blob/cf1efe6bbbae07ea6c45ef6cd5c0b4f2666b2e33/packages/chart-advisor/src/advisor.ts#L85

just like my data size: 140608...

**Comment by jiazhewang** [comment]
@Jeffy2012  we need a threshold in `typeAll` (and other similar APIs) of DataWizard.
