### ISSUE TITLE
The `translate` method is outdated, can not map to G2Plot 1.0's chart name.

### ISSUE THREAD

**Issue by simaQ** [antvis/AVA#43]
Like https://github.com/antvis/AVA/blob/master/packages/chart-advisor/src/util.ts#L29, it should be `StackedArea` in G2Plot 1.0.

**Comment by paleface001** [comment]
AVA目前依赖的还是G2Plot 0.x版本，升级版本后应该就不需要translate了

**Comment by jiazhewang** [comment]
This issue is related to #40 

The whole 'spec to libConfig' thing would be an individual tube in the pipeline.

I will publish a new version ASAP to solve that.

**Comment by jiazhewang** [comment]
solved in v0.1.3-alpha.27
