### ISSUE TITLE
@antv/auto-chart 示例图表样式异常

### ISSUE THREAD

**Issue by fy1231** [antvis/AVA#456]
求教这是什么原因呢？
<img width="1899" alt="截屏2022-06-09 19 33 48" src="https://user-images.githubusercontent.com/16006359/172837473-3c8fff7c-d0d7-43c3-9128-6779bc6f8ebc.png">
<img width="1899" alt="截屏2022-06-09 19 34 09" src="https://user-images.githubusercontent.com/16006359/172837490-763f602b-dd02-4329-9a53-6cc60ea3b8d3.png">

**Comment by BBSQQ** [comment]
引入样式文件了吗？可以试试在 css 文件中加一下
```
@import '~@antv/auto-chart/esm/index.css';
```
