### ISSUE TITLE
Issue in importing @antv/smart-board package via npm.

### ISSUE THREAD

**Issue by NoopurSystango** [antvis/AVA#459]
* **Package Name**: @antv/smart-board
* **Package Version**: 2.0.3

**Error**: ReferenceError: jLouvain is not defined at node_modules/louvain-algorithm/louvain.js

Refer Screenshot:
![Screenshot from 2022-06-28 16-14-42](https://user-images.githubusercontent.com/92789347/176160564-bd30e51b-ea79-496b-8845-426e12a594cd.png)

**Comment by ArranZeyuWang** [comment]
Seems to be missing dependences, try `npm i louvain-algorithm`

**Comment by NoopurSystango** [comment]
@ArranZeyuWang Still getting same error.

**Comment by vaibhav-systango** [comment]
@neoddish @WakuWaku-OuO @pddpd @BBSQQ I'm also facing the same issue !

**Comment by pddpd** [comment]
Hello, could you tell us the requirements for using SmartBoard?
