### ISSUE TITLE
能否提供一个callback告诉用户为什么无法生成图表

### ISSUE THREAD

**Issue by Engelce** [antvis/AVA#461]
* **Package Name**: @antv/chart-advisor   @antv/auto-chart
* **Package Version**: 2.0.3
* **Platform**: web
首先很感谢有这么一个有趣的项目，这是我在使用过程中发现的疑问，我现在有这么一份数据期望是生成一份[区间面积图](https://g2.antv.vision/zh/examples/area/range#range)，但是现在完全就是返回一个空数组根本不知如何去优化规则，希望能有个回调告诉用户是哪一环节导致了没有建议输出
`[{"time":"2022-06-15","data":476.392826298,"data_upper":495.065172929,"data_lower":457.5759700092,"trend":598.2811909585},{"time":"2022-06-16","data":544.9509984886,"data_upper":564.9018568801,"data_lower":525.6765509516,"trend":590.5529320864},{"time":"2022-06-17","data":746.9550012922,"data_upper":766.1727608202,"data_lower":727.4689209686,"trend":582.8246732422},{"time":"2022-06-18","data":671.0211435162,"data_upper":689.6065294327,"data_lower":650.8274736193,"trend":575.0964142905},{"time":"2022-06-19","data":722.0264841524,"data_upper":742.7081620709,"data_lower":702.1182679512,"trend":567.3681554517},{"time":"2022-06-20","data":392.0647964518,"data_upper":410.6013519512,"data_lower":371.6960021043,"trend":559.6398967498},{"time":"2022-06-21","data":425.1171988882,"data_upper":445.1005608379,"data_lower":406.9003537402,"trend":551.9116377422},{"time":"2022-06-22","data":484.1074084234,"data_upper":503.5309577653,"data_lower":465.128051293,"trend":544.1833782888},{"time":"2022-06-23","data":541.0520012607,"data_upper":560.1223130696,"data_lower":521.9859669707,"trend":536.455118947},{"time":"2022-06-24","data":704.961299288,"data_upper":724.9699721511,"data_lower":686.2785836691,"trend":528.7268592755},{"time":"2022-06-25","data":613.409204052,"data_upper":632.3290120709,"data_lower":593.9917549002,"trend":520.9985993622},{"time":"2022-06-26","data":588.9860373006,"data_upper":608.844570609,"data_lower":569.3590734545,"trend":513.2703394489},{"time":"2022-06-27","data":398.0066832343,"data_upper":416.9857104291,"data_lower":377.4021006277,"trend":505.5420795356},{"time":"2022-06-28","data":368.899693434,"data_upper":388.1011278737,"data_lower":350.5748031724,"trend":497.8138196222},{"time":"2022-06-29","data":421.9166266702,"data_upper":440.5286615655,"data_lower":404.0350011478,"trend":490.0855597089},{"time":"2022-06-30","data":472.1021223469,"data_upper":491.5161207621,"data_lower":454.4261521959,"trend":482.3572997956},{"time":"2022-07-01","data":620.2422941793,"data_upper":638.4480395197,"data_lower":601.1689327379,"trend":474.6290398823},{"time":"2022-07-02","data":543.3700787697,"data_upper":562.0333631997,"data_lower":525.4948902739,"trend":466.900779969},{"time":"2022-07-03","data":529.1102779019,"data_upper":547.3521621658,"data_lower":508.7065732081,"trend":459.1725200557},{"time":"2022-07-04","data":362.9685908372,"data_upper":382.6343447003,"data_lower":343.1341066573,"trend":451.4442601424},{"time":"2022-07-05","data":334.6993223192,"data_upper":353.6641359478,"data_lower":313.9568664156,"trend":443.7160002291},{"time":"2022-07-06","data":374.3583181065,"data_upper":394.3438258532,"data_lower":355.3278919883,"trend":435.9877403158},{"time":"2022-07-07","data":412.2915469024,"data_upper":431.8770372946,"data_lower":394.153545841,"trend":428.2594804025},{"time":"2022-07-08","data":543.0077046438,"data_upper":561.4437032514,"data_lower":524.059512839,"trend":420.5312204892},{"time":"2022-07-09","data":480.0351839701,"data_upper":498.5100122212,"data_lower":459.6713384409,"trend":412.8029605759},{"time":"2022-07-10","data":472.9429914589,"data_upper":492.2614492657,"data_lower":454.8431915979,"trend":405.0747006626},{"time":"2022-07-11","data":326.9464933128,"data_upper":346.2184044637,"data_lower":307.0172840567,"trend":397.3464407492}]`

**Comment by GuangMingYouBei** [comment]
你好，这个问题我们正在解。先提供一个暂时的解决方法。

就上述数据而言，可以转换成：
`[{"time":"2022-06-15", "type":  "data |  data_upper | data_lower | trend", "value": "xxx" }, ...  { }] `
这种形式，再输入给推荐算法，就可以生成你想要的图表了。
变换后，数据列 只剩一列 “value”，但是多了一列 分类列 “type”，把原本的 列头 “data |  data_upper | data_lower | trend” 都放到了这一列里面。
这种转换在 pandas 里对应的是 stack() 和 unstack() 方法。
参考：https://www.datasciencemadesimple.com/reshape-using-stack-unstack-function-pandas-python/

**Comment by Engelce** [comment]
再请问下，这个"value": "xxx"指代是什么，我要将数据各个字段对应的值填入么？比如`number[]`? 或者是纯string, `"326.9464933128 | 346.2184044637 | 307.0172840567"`?

**Comment by GuangMingYouBei** [comment]
举个例子，第一行
[{"time":"2022-06-15","data":476.392826298,"data_upper":495.065172929,"data_lower":457.5759700092,"trend":598.2811909585}]
转为:
[{"time":"2022-06-15", "type": "data", "value": 476.392826298 },
{"time":"2022-06-15", "type": "data_upper", "value": 495.065172929 },
{"time":"2022-06-15", "type": " data_lower", "value": 457.5759700092 },
{"time":"2022-06-15", "type": "trend", "value": 598.2811909585 }]

**Comment by Engelce** [comment]
那是转成二维数组还是继续保留一维数组全部都转成
[
{"time":"2022-06-15", "type": "data", "value": 476.392826298 },
{"time":"2022-06-15", "type": "data_upper", "value": 495.065172929 },
{"time":"2022-06-15", "type": " data_lower", "value": 457.5759700092 },
{"time":"2022-06-15", "type": "trend", "value": 598.2811909585 }
{"time":"2022-06-16", "type": "data", "value": 476.392826298 },
{"time":"2022-06-16", "type": "data_upper", "value": 495.065172929 },
{"time":"2022-06-16", "type": " data_lower", "value": 457.5759700092 },
{"time":"2022-06-16", "type": "trend", "value": 598.2811909585 },
]

**Comment by GuangMingYouBei** [comment]
还是一位数组："继续保留一维数组全部都转成"

**Comment by Engelce** [comment]
ok，我试下，thanks

**Comment by Engelce** [comment]
![image](https://user-images.githubusercontent.com/87524394/176405284-c32923a9-71e9-45fa-a6a8-5ac1e15997c7.png)
<img width="736" alt="image" src="https://user-images.githubusercontent.com/87524394/176405303-24ab33e0-5bf4-4140-bbf0-728a72f379a7.png">
还是给不出结果😂
