### ISSUE TITLE
请问，ava是纯前端框架吗？有后端语言的版本吗？

### ISSUE THREAD

**Issue by shangguansb** [antvis/AVA#462]
* **Package Name**:
* **Package Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

请问，ava是纯前端框架吗？有后端语言的版本吗？如java，go？有些数据集比较大，如上百万条，这样的运算量放在前端是否不太合适？有解决方案吗？

**Comment by neoddish** [comment]
你好。曾经有 python 方案，但是没有足够精力维护，所以也搁置了。目前就是前端框架。
针对数据量大的场景，确实建议后端有对应投入。可以参考 AVA 的方案实现。
