### ISSUE TITLE
AVA使用的一些疑问

### ISSUE THREAD

**Issue by womeng2009** [antvis/AVA#47]
1.图表可以不设定宽高，自适应父容器吗？
2.貌似没有提供图表数据刷新、配置刷新的方法，如何刷新数据？
3.图表有时候会显示异常，柱状图丢失一部分不显示，不知道什么原因
![image](https://user-images.githubusercontent.com/64006143/80180717-f4ff9280-8635-11ea-9ae3-6396ced3ae61.png)
但是在扇形图就是正常的，如下所示：
![image](https://user-images.githubusercontent.com/64006143/80180762-08126280-8636-11ea-82c5-a56448c5f262.png)

**Comment by jiazhewang** [comment]
生成后图表的问题，需要追溯对应使用的图表库。比如默认使用的是 G2Plot，建议查看其文档。
例如：3 中的问题很可能是把数值作为字符串类型传递的原因。
