### ISSUE TITLE
建议开发模式下的配置面板本地化

### ISSUE THREAD

**Issue by realeve** [antvis/AVA#5]
目前开发模式下的配置面板链接到 [https://render.alipay.com/p/s/autoChart/config-panel.html?type=Area&cancopydata=false](https://render.alipay.com/p/s/autoChart/config-panel.html?type=Area&cancopydata=false) 的独立html页面，能否单独开源出来用户自由部署。
目前的方案有两个问题：
1.该页面需要加载antd.js moment.js以及react.development.js等文件，载入时间较长，表现为打开时卡顿；

2.不方便内网部署。

## 最终效果类似下面这样：

![image](https://user-images.githubusercontent.com/448208/71874635-5ff78d00-315d-11ea-8222-e7da2bc1e7bc.png)

另外：参数中的cancopydata能否开发出来，默认为true;

**Comment by jiazhewang** [comment]
很好的建议，谢谢！
我们会考虑正式发布的时候，对面板的使用方式提供一个选择。

**Comment by jiazhewang** [comment]
关于 `cancopydata` ，目前当用户提供具体数据的时候，我们认为这个按钮没有必要展示。不希望增加用户的理解和交互成本。
