### ISSUE TITLE
结合g2plot使用AVA的一些问题

### ISSUE THREAD

**Issue by zogeli100** [antvis/AVA#59]
疑惑：
1.  AVA是否能支持交互事件的注册
```
  // 如onPlotClick等，尝试在导出的configs里配置,但是会报错
   events:{
      onPlotClick:(ev)=>{console.log(ev)}
   }
```
2.  AVA的文档（autochartoptions.md）太简洁了，部分内容不易理解，
- 比如toolbar似乎不是我理解的toolbar，配置开或关都没有对图表产生影响
3.  在实际的报表需求中会有图表切换，导出报表等特殊需求，需要一个工具栏（toolbar）可以自定义图标按钮用于功能的使用，如果本身不提供默认toolbar的话有没有什么入口允许自定义render工具栏。

> PS：在使用了AVA后确实是觉得可以更快速的生成配置参数，然后结合g2plot的文档再进行细化定制，效率感人。但是如果无法绑定事件，以及提供一些额外的参数配置入口（比如需要做图表和表格的切换功能，可能就需要自定义一个表格组件在toolbar点击切换的时候用表格覆盖当前图表，制造切换的效果）最后还是会因为需求覆盖率的问题不得不放弃AVA。

**Comment by neoddish** [comment]
抱歉回复晚了。
1、3： 目前 autoChart 作为一个研发态提效工具是不准备支持交互事件注册、toolbar 定制的。但是可以基于 pipeline 来自行封装：https://ava.antv.vision/zh/docs/guide/chart-advisor/pipeline

2： 文档部分官网已经完善：https://ava.antv.vision/zh/docs/api/chart-advisor/autoChart
关于 toolbar 的定义，确实是一个有歧义的命名。新提了一个 issue 来专门记录，会在下个大版本着重优化：https://github.com/antvis/AVA/issues/154

非常感谢你的反馈！
