### ISSUE TITLE
使用 getInsights 生成的分析结果里，饼图不完整

### ISSUE THREAD

**Issue by TopGrd** [antvis/AVA#631]
* **Package Name**: @antv/ava
* **Package Version**: 3.0.0
* **Platform**: Mac Chrome
* **Mini Showcase(like screenshots)**:  
<img width="668" alt="image" src="https://user-images.githubusercontent.com/4202848/227091090-30d1998e-9283-454d-ba9b-da27dc46e79c.png">

* **CodePen Link**:  https://codesandbox.io/s/brave-raman-vnnl4l?file=/src/Error.js

**Comment by chenluli** [comment]
感谢反馈。已在 @antv/ava 3.0.1 版本中修复，可以升级看下 🙇‍♀️
