### ISSUE TITLE
ava-react NarrativeTextVis onMouseEnterParagraph,onMouseLeaveParagraph 监听不灵敏

### ISSUE THREAD

**Issue by X-x-start** [antvis/AVA#634]
* **Package Name**:
* **Package Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

期望解决时间 4月7日前 @BBSQQ

**Comment by BBSQQ** [comment]
业务调整使用方法

**Comment by X-x-start** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，你的邮件我已经收到。
