### ISSUE TITLE
[SoC2020] Insight Workers for Insight Detection

### ISSUE THREAD

**Issue by jiazhewang** [antvis/AVA#64]
# 数据集洞察识别器的研发 <br> Insight Workers for Insight Detection

> What is SoC2020: #69 

##  描述 Description

[AVA](https://github.com/antvis/AVA) 是一套智能可视化解决方案，目前已经初步解决了从给定数据字段智能推荐和生成单个图表的问题，现阶段一个重要的目标是从多维数据集中自动识别出含有“洞察”的字段子集。比如，输入 20 列数据，能发现第 1、2 列存在相关关系；第 6 列的可选值中存在一个绝大占比的值；第 2、8 列形成的时序关系中存在几个异常值，等等。

我们为这个任务提供了一个简单的结构：[示例](https://github.com/antvis/AVA/blob/a7ac27b7b53ba37ca44fde1340601c6a90a36f3f/packages/chart-advisor/src/insight/index.ts)。结构中对每一种洞察定义了一个 InsightWorker，调用这个 InsightWorker 的特定方法可以检索出数据集中所有包含这种洞察类型的字段组合子集

[AVA](https://github.com/antvis/AVA) is a framework  for automated and augmented visual analytics. At present, the problem of recommendation and generation of a single chart from given data fields has been initially solved. An important goal at this stage is to automatically identify subsets of fields that containing "insights" from a multi-dimensional dataset. The insights include correlation, majority, outliers, etc.

We provide a [demo structure](https://github.com/antvis/AVA/blob/a7ac27b7b53ba37ca44fde1340601c6a90a36f3f/packages/chart-advisor/src/insight/index.ts) for this task. An InsightWorker is defined for each type of insight, and a specific method of this InsightWorker can retrieve subsets of all fields that contain this type of insight.

## 目标 Goal

参与研发部分 InsightWorkers，使它们能够服务于 AVA 的洞察识别功能：

1. 思考、调研并提出可能的洞察类型，指出其应用场景和分析价值。参考 [pbi 洞察（见解）类别](https://docs.microsoft.com/zh-cn/power-bi/consumer/end-user-insight-types)
1. 针对至少三个洞察类别的 InsightWorker 进行完整的开发工作。
1. 包括相关文档、测试的撰写。
1. 为这些 InsightWorker 编写易于测试和展示的 demo。参考：[示例](https://github.com/antvis/AVA/blob/insights/demo/FindInsightTest.tsx)
1. 这些 InsightWorker 应该可以与其他 InsightWorker 整合使用
1. 为每一种被识别出的洞察类别设计相关的最佳展示可视化。参考 [pbi 洞察（见解）类别](https://docs.microsoft.com/zh-cn/power-bi/consumer/end-user-insight-types)
1. 在研发过程中，如需使用到图表自动生成、数据预处理等环节的功能，学习并使用 AVA 的其他模块和 API 来完成（比如 [DataWizard](https://github.com/antvis/AVA/blob/master/packages/datawizard/zh-CN/README.zh-CN.md) 来处理数据）。如果 AVA 相关模块的能力不足以支持，则参与到这些模块的能力补全中去。

Participate in the development of some InsightWorkers so that they can serve the insight recognition.

1. Research and propose possible types of insights, pointing out their application scenarios and analytical value. See: [Power BI insight types](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-insight-types)
1. Complete development  on at least three InsightWorkers.
1. Write test cases and docs for them.
1. Write demos for these InsightWorkers to make them  easy to test and represent. See: [Examples](https://github.com/antvis/AVA/blob/insights/demo/FindInsightTest.tsx)
1. These InsightWorkers should be able to integrate with other InsightWorkers.
1. Design the best presentation visualization for each identified insight type. See: [Power BI insight types](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-insight-types)
1. packages.In the research and development process, if you need to use  features like automatic chart generation and data preprocessing, try modules and APIs of AVA (such as DataWizard to process data). If the capabilities of  AVA packages are not sufficient to support, then participate in the completion of the capabilities of these modules.

## 需要技能 Prerequisite Skills

1. 对数据可视化有基本理解，有可视化类库（如 G2/d3/echarts）的使用经验
1. 有 JavaScript、TypeScript、前端工程的基本能力
1. 有对数据分析、商业智能 BI 的基本了解和相关工具或产品的使用经验
1. 有良好的数学功底，有机器学习相关知识尤佳

<br>

1. Basic understanding of data visualization and experience in using visualization libraries (such as G2/d3/echarts).
1. JavaScript, TypeScript and front-end engineering skills.
1. Basic understanding of data analysis, business intelligence and experience in using related tools or products.
1. Good math skills, machine learning knowledge would be a plus.

**Comment by saphal1998** [comment]
Hey @jiazhewang, would love to work on this issue. Please help me with the next steps?

**Comment by jiazhewang** [comment]
> Hey @jiazhewang, would love to work on this issue. Please help me with the next steps?

You can check #69 for more instructions. First of all, visit https://www.alibabacloud.com/zh/campaign/summerofcode2020 and "Apply Now". Then follow the steps of this website.

As for the content of the proposal, I would suggest starting from the insight type, worker structure design and performance.

**Comment by jiazhewang** [comment]
> Hey @jiazhewang ,
> This idea seems pretty interesting to me and I would love to work on it this summer. Are there any discussions platform/channel or mailing list where we can discuss the project further?

Hi @hastagAB ,

Upon request, all discussions on the proposal must be made public. We can just discuss here.

BTW, the discussion under this [issue](https://github.com/antvis/G6/issues/1598) is a good example.

**Comment by hastagAB** [comment]
Hi @jiazhewang, I would like to get feedback on a few things (Please share your thoughts)

According to me, the most common and useful insights that we should work on are(Please share your views):
1. Time Series trends
2. Correlation, and
3. Outliers
> I will include the explanation, business use case with example input-output structure in my proposal.

For automated retrieval of these insights from data, I think Machine Learning would be really useful (especially when dealing with a huge dataset).

> 2. Complete development on at least three InsightWorkers.

By complete development, (if I'm not wrong) you mean building the logic part as well as integrating it with AVA framework for release.

> 6. Design the best presentation visualization for each identified insight type

A few visualizations are already there in this repo. I can use those and modify accordingly.

**Comment by jiazhewang** [comment]
## Types of Insights

Here is a [list](https://powerbi.microsoft.com/en-us/blog/announcing-power-bi-integration-with-cortana-and-new-ways-to-quickly-find-insights-in-your-data/) from Power BI

- Major factors 
- Category outliers 
- Time series outliers 
- Overall trends in time series 
- Seasonality in time series
- Steady Share
- Correlation
- Change points in a time series
- Low Variance

Of course, there are more. For example, correlation. Usually it means linear dependence, but maybe we can also have insight workers for nonlinear dependence of
two continuous variables.

## Implementation

Some ML algorithms are good options. But I also want to remind that the workers do not have to be complicated. They could use very simple algorithms as well. The key is accuracy and efficiency. 

This issue requires you to implement the logic parts as well as integrating it with AVA framework for release. 

Check the Power BI link above, each type of insight is presented by a specific kind of chart. Is this a best practice? We are not sure and we expect an answer (or better design) from you.

cc. @hastagAB

**Comment by hastagAB** [comment]
Hello @jiazhewang!

I did extensive research on various insight types and I've created a [Draft Proposal](https://gist.github.com/hastagAB/5d885b99439ba3bb3d952cb8eaa4e669) based on that.

Please do have a look and suggest any changes or add-ons, if required.

**Comment by jiazhewang** [comment]
> Hello @jiazhewang!
> 
> I did extensive research on various insight types and I've created a [Draft Proposal](https://gist.github.com/hastagAB/5d885b99439ba3bb3d952cb8eaa4e669) based on that.
> 
> Please do have a look and suggest any changes or add-ons, if required.

Hi @hastagAB ,

The draft is good!

Some suggestions:

1. It's great to sort out the priciples of each insight worker, it is one of the import challenges of this topic. However, another challeng is how to efficienty pass data through these workers (the performance). It would be even better if performance is mentioned in your proposal.
1. Check your timeline, I believe you don't need to allocate so many days to each single worker. Days can be saved for overall implementation and performance optimization. (btw, are there some copy-paste typos in the timeline?)
1. Could you mention your js/ts development experience in related chapter, plz? Or why do you think the js/ts language is not a problem for you. (I can see you are good at Python, the language itself may not be a problem but the answer of this question may make your proposal more convincing.)

BTW, just a friendly reminder that the submission of proposals expires June 30. Please submit your proposal once completing the modification.

best

**Comment by hastagAB** [comment]
Hey @jiazhewang 
I've done the modifications and submitted it on the portal. Can you please confirm if you received the proposal successfully?

I've written everything as per my understanding but if something isn't as per the requirements it can be discussed later and changed accordingly(If I got selected).

Hoping for the best!

**Comment by jiazhewang** [comment]
This project chose the proposal of @hastagAB . Congratulations!

BTW, any friends can still participate in the co-construction of this project or make suggestions. In addition to being an ASoC project, this task itself is still a help wanted issue. THX.
