### ISSUE TITLE
ava中推荐的图表antv-site-demo-rc中的ChartView的时候纵坐标内容较长时无法正常展示。

### ISSUE THREAD

**Issue by yuanAIhan** [antvis/AVA#660]
* **Package Name**:
* **Package Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
类似于官网的例子中，如果在代码中将数据修改为很大的时候。会出现如下图所示的效果。

目前推荐的图表只能使用antv-site-demo-rc中的ChartView来显示吗？其它库支持展示吗？
https://ava.antv.antgroup.com/zh/examples/advice/advisor-only/#advisor-steps

![image](https://user-images.githubusercontent.com/80769611/235044246-66813471-4659-4cb0-aef0-aa454cf62add.png)

**Comment by GuangMingYouBei** [comment]
<ChartView /> 其实只是在 G2 5.0 上封装了一层组件，本质上还是 G2 5.0 渲染的。
AVA 推荐结果的核心是 `spec`，
`const plotContent = <ChartView chartRef={this.myRef} spec={advices[currentAdvice].spec} />;`
即这段代码里的 `advices[currentAdvice].spec `，
G2 5.0 可以直接基于这个 spec 渲染，参照这个文档：
[https://g2.antv.antgroup.com/manual/more/experimental-spec-api](url)

**Comment by chenluli** [comment]
坐标轴标签无法展示全应该是因为目前 G2 没有自动识别和预留轴标签需要的空间( cc @pearmini 如果 G2 这个问题有进展可以同步下🙇‍♀️，另外 @GuangMingYouBei 可以看下是否要 AVA 侧先默认加一个 padding / 轴标签格式化）

目前可以通过在产生的 spec (`advices[currentAdvice].spec`)中手动加上 `paddingLeft` 属性解决
