### ISSUE TITLE
【咨询】是否提供钉钉or微信交流群🥰

### ISSUE THREAD

**Issue by KS-OTO** [antvis/AVA#663]
最近在借助AVA进行项目开发，有一些工程和实现问题，想方便交流/答疑，不知道官方是否有钉钉 or 微信交流群？

_小插曲，我把羽雀文档、wiki、bing都翻了（搜索）个遍，都没有找到AVA的群，其他的L7、G2、S2都找到了，所以issue问下😳😳😳
<-- ^_^ -->

**Comment by chenluli** [comment]
你好，目前 AVA 暂时没有开交流群的计划，交流和答疑等任何问题都欢迎通过 discussions 和我们交流 👉 https://github.com/antvis/AVA/discussions 

discussions中的任何问题，我们都会及时进行回复的，也有利于其他有类似需求和疑问的用户看见讨论内容～
