### ISSUE TITLE
如何推荐的图表使用G2来渲染的时候，当横坐标很多，即数据很多的时候，渲染出来的图形会出现坐标轴重合。

### ISSUE THREAD

**Issue by yuanAIhan** [antvis/AVA#672]
* **Package Name**:
* **Package Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

我使用下面的代码实现的
const chart = new Chart({
      container: container as string | HTMLElement,
      theme: 'classic',
      autoFit: true,
      width: width,
      height: height,
    })
  // 声明可视化
  chart.options({
    type: specValue?.type, // 创建一个 Interval 标记
    data: specValue?.data,
    encode: specValue?.encode,
    paddingLeft: 80,
  })
  chart.scale({
    x: {
      nice: true, // 对x轴坐标点进行优化
    },
    y: {
      nice: true, // 对y轴坐标点进行优化
    },
  })
  chart.render()
最终出现的图像如下所示：
![image](https://github.com/antvis/AVA/assets/80769611/8f9ded73-6bfe-4da9-84d9-35d6ee3c23fc)
我尝试了很多g2支持的调整坐标轴样式的方式，但是最终都没有效果。
比如：
chart.scale('x', {
  tickCount: 5,
});
请问这个是因为chart.options导致的问题吗？还是我哪里的使用方式不正确导致的呀？

**Comment by pearmini** [comment]
目前 chart.options 和 其他 chart api 不能混用，可以如下声明：

```js
chart.options({
  type: specValue?.type, // 创建一个 Interval 标记
  data: specValue?.data,
  encode: specValue?.encode,
  paddingLeft: 80,
  scale: { x: { nice:true }, y: { nice: true} },
  axis: { x: tickCount: 5, autoHide: true }
})
```
