### ISSUE TITLE
antv-site-demo-rc库中的ChartView无法使用

### ISSUE THREAD

**Issue by Lam688** [antvis/AVA#731]
* **Package Name**:
* **Package Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

将spec原封不动传递给ChartView为什么报错？
![image](https://github.com/antvis/AVA/assets/86229727/56f35c68-9db6-4190-bd80-a6aff257f176)
<img width="684" alt="1695119956131" src="https://github.com/antvis/AVA/assets/86229727/a530b4b6-03e6-4eec-96c7-d194c1b9fb8e">
版本：
"@antv/ava": "^3.0.7",
"@antv/ava-react": "^3.1.9",
"antv-site-demo-rc": "^1.1.0",

**Comment by Lam688** [comment]
而且antv-site-demo-rc这个库安装的时候编译就报错，缺少react-json-view的路径，单独装了一下react-json-view编译才通过。

**Comment by Lam688** [comment]
推荐出来的spec数据只能使用这个组件渲染出来吗？

**Comment by chenluli** [comment]
> 推荐出来的spec数据只能使用这个组件渲染出来吗？

AVA 中推荐出来的 spec 遵循 AntV G2 spec 的语法，可以用 G2 进行渲染，参考 G2 的 examples 中的 spec 模式写法 https://g2.antv.antgroup.com/examples

ChartView 组件仅用于 AVA 官网演示用，内部只是调用了下 G2 （https://github.com/neoddish/antv-site-demo-rc/blob/main/src/ChartView/index.tsx），看报错可能是 g2 的依赖版本不对？推荐自行调用 G2 渲染

**Comment by Lam688** [comment]
> > 推荐出来的spec数据只能使用这个组件渲染出来吗？
> 
> AVA 中推荐出来的 spec 遵循 AntV G2 spec 的语法，可以用 G2 进行渲染，参考 G2 的 examples 中的 spec 模式写法 https://g2.antv.antgroup.com/examples
> 
> ChartView 组件仅用于 AVA 官网演示用，内部只是调用了下 G2 （[https://github.com/neoddish/antv-site-demo-rc/blob/main/src/ChartView/index.tsx），看报错可能是](https://github.com/neoddish/antv-site-demo-rc/blob/main/src/ChartView/index.tsx%EF%BC%89%EF%BC%8C%E7%9C%8B%E6%8A%A5%E9%94%99%E5%8F%AF%E8%83%BD%E6%98%AF) g2 的依赖版本不对？推荐自行调用 G2 渲染


谢谢，这个问题解决了，那lint的优化，除了antv-site-demo-rc中的LintCard之外，可以用什么展示？

**Comment by Lam688** [comment]
用antd中的List渲染lint的信息的话，可以格式化成中文吗，Lint中有没有对应的国际化接口？

**Comment by chenluli** [comment]
> 用antd中的List渲染lint的信息的话，可以格式化成中文吗，Lint中有没有对应的国际化接口？

lint 输出的结构是包含 rule id 和对应的规则 docs，展示的信息是 `docs.lintText` 中的，目前内置的是英文的，如果需要定制成中文目前应该需要自己根据 rule id 对应的含义自定义 lintText 信息 https://ava.antv.antgroup.com/guide/advice/rules#%E6%8E%A8%E8%8D%90%E8%A7%84%E5%88%99%E4%B8%80%E8%A7%88 

也欢迎给我们提 PR / feature request，补充内置的中文输出 😊
