### ISSUE TITLE
请问支持折柱图的渲染吗

### ISSUE THREAD

**Issue by ccckdi** [antvis/AVA#732]
* **Package Name**:
* **Package Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by chenluli** [comment]
AVA 的图表推荐中目前还没有涵盖折柱图，目前可推荐出的图表类型参考：https://ava.antv.antgroup.com/api/ckb/constants
另外 AVA 本身不处理图表渲染，渲染能力是基于 G2 进行的 https://g2.antv.antgroup.com/examples，可以参考 G2 的示例进行折柱图的渲染。
