### ISSUE TITLE
Cannot find module 'react' or its corresponding type declarations.

### ISSUE THREAD

**Issue by cipchk** [antvis/AVA#737]
* **Package Name**: @antv/g2
* **Package Version**: 3.1.0
* **Platform**: Browser
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

Angular 项目，只引用 `@antv/g2@^5.1.6` 会有以下错误：

```
Error: node_modules/@antv/ava/lib/ntv/schema/common.d.ts:1:36 - error TS2307: Cannot find module 'react' or its corresponding type declarations.

1 import type { CSSProperties } from 'react';
```

希望不要有依赖 `react`，除非明确在使用 [@antv/ava-react](https://www.npmjs.com/package/@antv/ava-react)。

**Comment by chenluli** [comment]
@BBSQQ  看了下是 ntv schema 里依赖到 CSSProperties 这个类型了，改成从 csstype 引用类型？

**Comment by BBSQQ** [comment]
> @BBSQQ 看了下是 ntv schema 里依赖到 CSSProperties 这个类型了，改成从 csstype 引用类型？

应该可以的，来cr下：https://github.com/antvis/AVA/pull/739
