### ISSUE TITLE
[nextjs] after install antv/ava, error:Fatal JavaScript invalid size error 169220804

### ISSUE THREAD

**Issue by ZhinanCai** [antvis/AVA#782]
* **Package Name**:@antv/ava
* **Package Version**:^3.4.1
* **Platform**:node 18.18
* **Mini Showcase(like screenshots)**:
![image](https://github.com/antvis/AVA/assets/55445846/02a8c96a-b84e-48c8-8cd7-00eb307bd751)

* **CodePen Link**:

in nextjs,i install the package "@antv/ava": "^3.4.1",then i npm  run dev.
the error occur below:
#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 169220804
#
#
#
#FailureMessage Object: 0x16d780708
 1: 0x1027935e0 node::NodePlatform::GetStackTracePrinter()::$_3::__invoke() [/usr/local/bin/node]
 2: 0x103709bf8 V8_Fatal(char const*, ...) [/usr/local/bin/node]
 3: 0x102a061b4 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/usr/local/bin/node]
 4: 0x102b9c080 v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::GrowCapacity(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/usr/local/bin/node]
 5: 0x102da2fe0 v8::internal::Runtime_GrowArrayElements(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
 6: 0x1030fd04c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
 7: 0x1083ada80 
 8: 0x1083acae8 
 9: 0x1083e6ea0 
10: 0x1030864d0 Builtins_JSEntryTrampoline [/usr/local/bin/node]
11: 0x103086164 Builtins_JSEntry [/usr/local/bin/node]
12: 0x1029b79dc v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
13: 0x1029b6f1c v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/usr/local/bin/node]
14: 0x1028a711c v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/usr/local/bin/node]
15: 0x102678d08 node::InternalCallbackScope::Close() [/usr/local/bin/node]
16: 0x102678fd0 node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
17: 0x10268e36c node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/usr/local/bin/node]
18: 0x102738df8 node::fs::FSReqCallback::Resolve(v8::Local<v8::Value>) [/usr/local/bin/node]
19: 0x1027396f0 node::fs::AfterStat(uv_fs_s*) [/usr/local/bin/node]
20: 0x10272fbb0 node::MakeLibuvRequestCallback<uv_fs_s, void (*)(uv_fs_s*)>::Wrapper(uv_fs_s*) [/usr/local/bin/node]
21: 0x103064070 uv__work_done [/usr/local/bin/node]
22: 0x103067ac0 uv__async_io [/usr/local/bin/node]
23: 0x103079b98 uv__io_poll [/usr/local/bin/node]
24: 0x103068084 uv_run [/usr/local/bin/node]
25: 0x1026796e0 node::SpinEventLoop(node::Environment*) [/usr/local/bin/node]
26: 0x102770850 node::NodeMainInstance::Run() [/usr/local/bin/node]
27: 0x1027006a4 node::LoadSnapshotDataAndRun(node::SnapshotData const**, node::InitializationResult const*) [/usr/local/bin/node]
28: 0x10270095c node::Start(int, char**) [/usr/local/bin/node]
29: 0x191edbe50 start [/usr/lib/dyld]

please help

**Comment by chenluli** [comment]
Hello, I have attempted to reproduce the problem, but I haven't been able to observe the error you described. For your reference, here is the link to the CodeSandbox demonstrating using ava with nextjs: [codesandbox link](https://codesandbox.io/p/devbox/hdj3km?migrateFrom=rrv347&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwh7j5wq00063b6jscpcg7ec%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwh7j5wq00023b6jyd0fv4zv%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwh7j5wq00043b6ju6hsp538%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwh7j5wq00053b6jwfqrv72i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwh7j5wq00023b6jyd0fv4zv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwh7j5wp00013b6j3158o9k5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%257D%255D%252C%2522id%2522%253A%2522clwh7j5wq00023b6jyd0fv4zv%2522%252C%2522activeTabId%2522%253A%2522clwh7j5wp00013b6j3158o9k5%2522%257D%252C%2522clwh7j5wq00053b6jwfqrv72i%2522%253A%257B%2522id%2522%253A%2522clwh7j5wq00053b6jwfqrv72i%2522%252C%2522activeTabId%2522%253A%2522clwh7ufs200hg3b6jybxtegdc%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clwh7ufs200hg3b6jybxtegdc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clwh7j5wq00043b6ju6hsp538%2522%253A%257B%2522id%2522%253A%2522clwh7j5wq00043b6ju6hsp538%2522%252C%2522activeTabId%2522%253A%2522clwh7wwgs00jt3b6jvqlb7dv1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwh7j5wq00033b6jcf64nk3j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwh7j6bc000hdjf8ewok1zfi%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clwh7jflu007p3b6j3ed6vucl%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clwh7wwgs00jt3b6jvqlb7dv1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwh7wwn5004odjf840mbelub%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D). From the error information you've shared, it seems that the issue might be related to memory leaks or oversized memory allocations. Would you be able to confirm if the issue persists even when ava is not loaded? 

To assist in diagnosing the problem further, could you please provide a code sandbox demo or minimal code snippet that replicates the issue?
