### ISSUE TITLE
an infinite loop problem

### ISSUE THREAD

**Issue by Tomotoes** [antvis/AVA#787]
* **Package Name**: @antv/ava
* **Package Version**:3.0.7
* **Platform**: nodejs

[183ceb51-e335-49f9-ad05-413538f4810b.cpuprofile](https://github.com/user-attachments/files/16096061/183ceb51-e335-49f9-ad05-413538f4810b.cpuprofile)
The cpuprofile can be downloaded. There is an infinite loop problem.
<img width="2098" alt="image" src="https://github.com/antvis/AVA/assets/32236122/b113aec0-3993-45fb-a4c6-ba38857aa49c">

**Comment by chenluli** [comment]
The issue has been resolved in #777, please upgrade to version 3.4.1+.

**Comment by maisui99** [comment]
![image](https://github.com/user-attachments/assets/6dde7396-821e-4607-86c4-7a43fd8f10c8)
![image](https://github.com/user-attachments/assets/582a0891-2fa4-4831-a241-70b60b014f2f)

There is still an infinite loop problem in 3.4.1.
