### ISSUE TITLE
扩展性问题

### ISSUE THREAD

**Issue by babyfacer0104** [antvis/AVA#86]
请问下，几时有正式版？对其他其他插件图表是否有智能识别？

**Comment by jiazhewang** [comment]
预计 11 月底会发布正式版。其他插件图表指的是什么？

**Comment by babyfacer0104** [comment]
可扩展组件，有些业务需求场景需要用到，比如：地图，地球，还有一些3D图表；
疑问：
1. 右边里面config配置里能否可扩展一些属性和config按钮的位置（颜色，排序...）；
2. 左边推荐位置有接口可以调整位置吗？

**Comment by babyfacer0104** [comment]
可扩展组件，有些业务场景需要用到，比如：地图，地球，还有一些3D图表；
疑问点：
右边显示config按钮是否可设置扩展属性（颜色，排序...）和config按钮的位置？
左边显示推荐按钮位置有接口可以调整位置吗？

**Comment by jiazhewang** [comment]
目前支持的图表类型还是主要针对基础统计图表，以后会慢慢优化到其他的，比如 graph，比如地图。如果有需求可以提，更欢迎共建~~

关于 config 按钮我们现在在还没有支持这些能力，这些排序一类的交互我们可能会有其他方案来实现，非常感谢这种需求输入。
目前 autoChart 支持的按钮位置还不能修改，有这方面需求吗？是希望上线的产品里透出这个按钮？

**Comment by babyfacer0104** [comment]
在使用过程，把源代码看了一遍，学到很多规范代码方面的知识；
使用过程一些问题：
 现基础图表，暂时缺地图不能满足；
 在使用过程发现，最高评分的图表并不是当前渲染的图表，不知道怎么获取当前源码里打印的console.log(type)？
 修改config样式等配置，无法重新渲染，只有render，update不了
使用瓶颈：
config和推荐功能比较少就没继续用了~
是希望上线的产品里透出这个按钮的，可以用在动态可视化渲染场景，但看现有功能比较少，扩展不了其他功能，比如修改颜色，参照你们的config重新写一套了~
柱状图度量在最高数值，label设置top时看不到数值了~
希望期待更多的API …

**Comment by jiazhewang** [comment]
@babyfacer0104 感谢你的持续反馈，几个不完备的点我们会继续优化。也非常期待你可以参与进来哈

**Comment by babyfacer0104** [comment]
autoChart对饼如何设置才能自动转换为百分号？

**Comment by pddpd** [comment]
We will provide the new `<AutoChart />` in ava-react 3.x

**Comment by chenluli** [comment]
关于 AutoChart 组件，可以关注这个 issue: https://github.com/antvis/AVA/issues/635
