### ISSUE TITLE
CKB Completion 图表知识库补全计划

### ISSUE THREAD

**Issue by neoddish** [antvis/AVA#90]
目前我们的[图表知识库（CKB）](https://github.com/antvis/AVA/tree/master/packages/knowledge)还有很多信息不完备，急需社区合力讨论、补充。

At present, our [Chart Knowledge Base](https://github.com/antvis/AVA/tree/master/packages/knowledge) still has a lot of incomplete information, which urgently needs the community to discuss and supplement together.

关于为什么要做 CKB，这篇文章进行了解释：[《AVA/CKB：一次性解决图表命名问题》](https://zhuanlan.zhihu.com/p/110864643)

This article explains why CKB is required: "[AVA/CKB: Solving the Chart Naming Problem at One Time](https://zhuanlan.zhihu.com/p/110864643)" (Sorry, only the Chinese version is available)

## 如何贡献 How to contribute

请参考我们的 [CKB 贡献指南](https://github.com/antvis/AVA/blob/master/packages/knowledge/zh-CN/CONTRIBUTING.zh-CN.md)，里面有操作细节，感谢！

Please refer to our [CKB contribution guide](https://github.com/antvis/AVA/blob/master/packages/knowledge/CONTRIBUTING.md), which has operational details, thanks!

**Comment by jiazhewang** [comment]
https://github.com/antvis/G2Plot/blob/master/src/index.ts

as reference

**Comment by jiazhewang** [comment]
# 鸣谢 Acknowledgement

@ymyqwe - treemap
