### ISSUE TITLE
1122 site theme picture

### ISSUE THREAD

**Issue by BBSQQ** [antvis/AVA#91]
本年度 AntV 品牌日 AVA 将开源产品网站，现向社区征集主站主题图片🌟 ，放置如下图的位置。有意向的设计师 / 工程师欢迎来撩～～
![image](https://user-images.githubusercontent.com/35586469/98665878-36b01a80-2387-11eb-8b0d-e742517359a9.png)

**Comment by GaiaPang** [comment]
举手投稿～
![AVA_themepic](https://user-images.githubusercontent.com/40760576/99162804-d5989600-273c-11eb-920c-f94226e38725.png)

**Comment by jiazhewang** [comment]
@GaiaPang would u submit a zip for SVG format, plz? thx

**Comment by GaiaPang** [comment]
@jiazhewang OK!
[AVA_themepic.svg.zip](https://github.com/antvis/AVA/files/5541862/AVA_themepic.svg.zip)

**Comment by jiazhewang** [comment]
@GaiaPang

**Comment by GaiaPang** [comment]
@jiazhewang 
https://github.com/antvis/AVA/pull/99

**Comment by jiazhewang** [comment]
perfect! thx @GaiaPang
